[build]
  base = "client"
  publish = ".next"
  command = "/bin/bash -c 'pnpm install && pnpm add -D typescript@5.3.3 @types/react@18.3.14 @types/node@20.17.9 && NODE_ENV=development pnpm run build'"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://tulpar-express.netlify.app"
  NODE_VERSION = "18.17.0"
  NEXT_PUBLIC_API_URL = "https://api.te.kg"
  NEXT_PUBLIC_SUPABASE_URL = "https://eacpkbrvpxhejgwyziwd.supabase.co"
  NEXT_PUBLIC_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVhY3BrYnJ2cHhoZWpnd3l6aXdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDE5NTk5NDAsImV4cCI6MjAxNzUzNTk0MH0.1CAOvhWWxHBzEQEbTJvRjFAEKTlX2-yWVnRzpg-VBMU"
  NETLIFY_USE_PNPM = "true"
  NETLIFY_NEXT_CACHE = "true"
  SHELL = "/bin/bash"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[dev]
  framework = "next"
  targetPort = 3000

# Настройки для разных окружений
[context.production]
  environment = { NODE_ENV = "production" }

[context.deploy-preview]
  environment = { NODE_ENV = "preview" }

[context.branch-deploy]
  environment = { NODE_ENV = "development" }
